[package]
name = "challenge3"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-graphics = "0.7.1"
embedded-hal = "0.2.3"
longan-nano = { version = "0.3.0", features = ["lcd"] }
panic-halt = "0.2.0"
riscv-rt = "0.8.0"
riscv = "0.7.0"
